/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useTexture, Center, Decal } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/MAD_KING_armchair950_.gltf");
  const texture = useTexture("/1200px-Starbucks_Logo_ab_2011.svg.png");
  // Update the material to use the loaded texture
  // materials["01 - Default"].map = texture;
  // materials["01 - Default"].needsUpdate = true;
  return (
    <>
      <group {...props} dispose={null}>
        <Center top>
          <mesh
            name="MAD_KING_armchair950_001"
            scale={0.1}
            castShadow
            receiveShadow
            geometry={nodes.MAD_KING_armchair950_001.geometry}
            material={materials["01 - Default"]}
            position={[1.2, -12, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <Decal
              position={[0, 0, 0]} // Adjust position relative to the mesh
              rotation={[0, 0, 0]} // Adjust rotation as needed
              scale={[0.5, 0.5, 0.5]} // Adjust scale as needed
              map={texture}
            />
          </mesh>
        </Center>
      </group>
    </>
  );
}

useGLTF.preload("/models/MAD_KING_armchair950_.gltf");
