/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useTexture, Center, Decal } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/MAD_KING_armchair950_.gltf");
  const texture = useTexture(`/maps/${props.texture}`);
  // Update the material to use the loaded texture
  materials["01 - Default"].map = texture;
  materials["01 - Default"].needsUpdate = true;
  return (
    <>
      <group {...props} dispose={null}>
        <Center middle position={[0, 1, 0]}>
          <mesh
            name="MAD_KING_armchair950_001"
            scale={0.1}
            castShadow
            receiveShadow
            geometry={nodes.MAD_KING_armchair950_001.geometry}
            material={materials["01 - Default"]}
            position={[1.2, -13, 0]}
            rotation={[-Math.PI / 2.5, 0, 0]}
          ></mesh>
        </Center>
      </group>
    </>
  );
}

useGLTF.preload("/models/MAD_KING_armchair950_.gltf");
